// src/classes/ovary.d/iso.ts
import { IEggsConfig } from "../settings.ts";
import { Constants } from "../constants.ts";
import { Utils } from "../utils.ts";
import { IDistroInfo } from "../distro.ts";
import { path, ensureDir, exists } from "../../deps.ts";

export class Iso {
  private config: IEggsConfig;
  private distro: IDistroInfo;

  constructor(config: IEggsConfig, distro: IDistroInfo) {
    this.config = config;
    this.distro = distro;
  }

  async build(options: any) {
    Utils.title("💿 ISO: Building Hybrid Image");

    const isoWork = path.join(Constants.NEST, "iso"); 
    
    // Nomi file sicuri
    const safeDistroId = this.distro.distribId.replaceAll(" ", "_").replaceAll("/", "-");
    const safeCodename = this.distro.codename.replaceAll(" ", "_");
    
    // Costruzione nome ISO: egg-of-[familyId]-[codename/releaseId]-[hostname]-[date-time].iso
    const family = this.distro.familyId || this.distro.id;
    const version = (this.distro.codename && this.distro.codename !== "unknown") 
      ? this.distro.codename 
      : this.distro.releaseId;
      
    // safe version
    const safeVersion = version.replaceAll(" ", "_").toLowerCase();
    const safeFamily = family.replaceAll(" ", "_").toLowerCase();

    // Recupero Hostname
    let hostname = "unknown";
    if (await exists("/etc/hostname")) {
       hostname = (await Deno.readTextFile("/etc/hostname")).trim();
    }
    
    // Recupero Data/Ora (YYYYMMDD_HHmm)
    const now = new Date();
    const yyyy = now.getFullYear();
    const mm = String(now.getMonth() + 1).padStart(2, "0");
    const dd = String(now.getDate()).padStart(2, "0");
    const hh = String(now.getHours()).padStart(2, "0");
    const min = String(now.getMinutes()).padStart(2, "0");
    const dateTime = `${yyyy}${mm}${dd}_${hh}${min}`;
    
    const isoName = `${this.config.snapshot_prefix}-${safeFamily}-${safeVersion}-${hostname}-${dateTime}.iso`;
    const mntDir = path.join(Constants.NEST, "mnt");
    await ensureDir(mntDir);
    const isoPath = path.join(mntDir, isoName);

    // Volume ID (Max 32 chars, Uppercase)
    let volId = `${this.config.snapshot_prefix}_${safeDistroId}_${safeCodename}`.toUpperCase();
    volId = volId.replace(/[^A-Z0-9_]/g, "_");
    if (volId.length > 30) volId = volId.substring(0, 30);

    // Generazione checksums interni
    await this.generateChecksums(isoWork);

    // --- XORRISO COMMAND ---
    // Usiamo ISOLINUX per il BIOS (legacy) e GRUB per EFI
    const xorrisoArgs = [
        "-as", "mkisofs",
        "-iso-level", "3",
        "-full-iso9660-filenames",
        "-volid", volId,
        "-output", isoPath,
        
        // --- BIOS BOOT (Legacy / CD) ---
        // Usiamo isolinux.bin invece di bios.img
        "-b", "isolinux/isolinux.bin",       // Il file binario di boot
        "-c", "isolinux/boot.cat",           // Il catalogo (verrà creato da xorriso)
        "-no-emul-boot",
        "-boot-load-size", "4",
        "-boot-info-table",
        
        // --- EFI BOOT (UEFI) ---
        "-eltorito-alt-boot",
        "-e", "EFI/efiboot.img",
        "-no-emul-boot",
        "-isohybrid-gpt-basdat",             // Crea tabella partizioni ibrida GPT
        
        isoWork
    ];

    // --- SCRIPT GENERATION ---
    const binDir = path.join(Constants.NEST, "bin");
    await ensureDir(binDir);
    const scriptFile = path.join(binDir, "mkiso.sh");
    
    // Construct command string for script
    // Quote arguments that might contain spaces or special chars
    const scriptArgs = xorrisoArgs.map(arg => {
        if (arg === isoWork || arg === isoPath || arg.includes(" ")) {
            return `"${arg}"`;
        }
        return arg;
    });
    
    const scriptContent = [
        "#!/bin/bash",
        "# Auto-generated by eggs-of-deno",
        "",
        `xorriso ${scriptArgs.join(" ")}`,
        ""
    ].join("\n");

    await Deno.writeTextFile(scriptFile, scriptContent);
    await Deno.chmod(scriptFile, 0o755);
    console.log(`📝 Script mkiso generato: ${scriptFile}`);

    console.log(`-> Creating ISO: ${isoName}`);
    console.log(`-> Boot Strategy: ISOLINUX (Bios) + GRUB (Efi)`);

    const result = await Utils.run("xorriso", xorrisoArgs, true);
    const isoCreated = await exists(isoPath);

    if (result.success || (isoCreated && result.code === 32)) { // Tolleranza codice 32
        console.log(`\n✅ ISO Created Successfully!`);
        console.log(`📂 Path: ${isoPath}`);
        
        console.log("-> Calculating ISO checksum...");
        await Utils.run("sh", ["-c", `md5sum ${isoPath} > ${isoPath}.md5`]);
        console.log("✅ Checksum ready.");
    } else {
        throw new Error("ISO Creation Failed");
    }
  }

  private async generateChecksums(isoWork: string) {
    console.log("-> Generating internal md5sum.txt...");
    // Escludiamo i file di boot dal checksum interno per evitare loop strani
    const cmd = `cd ${isoWork} && find . -type f -not -name 'md5sum.txt' -not -path '*/isolinux/*' -not -path '*/EFI/*' -print0 | xargs -0 md5sum > md5sum.txt`;
    await Utils.run("sh", ["-c", cmd]);
  }
}
